web:
   image: rafiq/php7.2-mysqli
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "8080:80"
   links:
     - db
   volumes:
     - ./app:/var/www/html/

db:
  image: mariadb
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: kbt_poc_2019
  ports:
    - "3306:3306"

phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  links:
    - db
  ports:
    - 8890:80
  environment:
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: kbt_poc_2019
